name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Nombre del paso -name
    - name: Checkout code
      uses: actions/checkout@v4
      # Busqueda de historial de commit muy profundo
      with:
        fetch-depth: 0
        
    # Logarse en docker
    - name: Docker login
      # Crear variables de entorno
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # | Significa que cada l√≠nea se ejecuta independientemente
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    # Construccion y subida a nube
    - name: Build Docker Image
      run: |
        docker build -t kjsaldana/docker-graphql:0.0.2 .
                
    - name: Push Docker Image
      run: |
        docker push kjsaldana/docker-graphql:0.0.2
