name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Nombre del paso -name
    - name: Checkout code
      uses: actions/checkout@v4
      # Config, busqueda de historial de commit muy profundo
      with:
        fetch-depth: 0

    # Control de la versión de app
    - name: Git Semantic Version
      # id global
      id: version
      uses: PaulHatch/semantic-version@v5.4.0
      # Config, cambiar triggers
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}"
        
    # Logarse en docker
    - name: Docker login
      # Crear variables de entorno
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # "|" Significa que cada línea se ejecuta independientemente
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    # Construccion y subida a nube
    - name: Build Docker Image
      env:
        # Seleccionar un paso "-", luego el id, luego output y version del action
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t kjsaldana/docker-graphql:NEW_VERSION .
        docker build -t kjsaldana/docker-graphql:latest .
                
    - name: Push Docker Image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push kjsaldana/docker-graphql:$NEW_VERSION
        docker push kjsaldana/docker-graphql:latest
